server:
  port: 8884

spring:
  application:
    name: zuul

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #efaultZone: http://172.16.0.5:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: zuul
    prefer-ip-address: true     #访问路径可以显示IP地址
zuul:
  routes:
    provider.serviceId: ORDER-PROVIDER   #隐藏要访问的微服务名更改为下面的path即为provider
    provider.path: /provider/**
  #ignored-services: ORDER-PROVIDER  #忽略原真实服务地址，即不可通过该服务名访问 如: http://127.0.0.1:8884/order-provider/product/getProduct?id=1
  ignored-services: "*"             #忽略全部真实地址
  prefix: /fix                      #添加地址前缀
  retryable: true                   #开启zuuk网管重试

