spring:
  profiles:
    active:
      - test
---
server:
  port: 8882

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件
  type-aliases-package: com.order.entities.*    # 所有Entity别名类所在包
  # config-location:
  configuration:
    cache-enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #efaultZone: http://172.16.0.5:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: ORDER-PROVIDER-TEST-Change
    prefer-ip-address: true     #访问路径可以显示IP地址

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

spring:
  profiles: test
  application:
    name: ORDER-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    #url: jdbc:mysql://112.74.73.24:3306/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8
    url: jdbc:mysql://47.114.135.132:4406/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8              # 数据库名
    username: root
    #password: lin
    password: kangbei123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    #database: 0
    host: 47.114.135.132
    port: 6100
      #cluster:
      #nodes: 112.74.73.24:6381,112.74.73.24:6382,112.74.73.24:6383,112.74.73.24:6384,112.74.73.24:6385,112.74.73.24:6386
    #max-redirects: 3
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1ms
    password: kangbei123

# 打印sql
logging:
  level:
    com.order.mapper : debug
mybatis-plus:
  type-aliases-package:
  mapper-locations:
  global-config:
    refresh-mapper: true
    #驼峰下划线转换
    column-underline: true
  configuration:
    map-underscore-to-camel-case: true

---
server:
  port: 8882

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件
  type-aliases-package: com.order.entities.*    # 所有Entity别名类所在包
  # config-location:
  configuration:
    cache-enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://172.16.0.5:7001/eureka
      #defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: ORDER-PROVIDER-DEV
    prefer-ip-address: true     #访问路径可以显示IP地址

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

spring:
  profiles: dev
  application:
    name: ORDER-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    #url: jdbc:mysql://112.74.73.24:3306/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8
    url: jdbc:mysql://47.114.135.132:4406/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/order?useUnicode=true&autoReconnect=true&characterEncoding=utf8              # 数据库名
    username: root
    #password: lin
    password: kangbei123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    #database: 0
    host: 47.114.135.132
    port: 6100
      #cluster:
    #nodes: 112.74.73.24:6381,112.74.73.24:6382,112.74.73.24:6383,112.74.73.24:6384,112.74.73.24:6385,112.74.73.24:6386
    #max-redirects: 3
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1ms
    password: kangbei123

# 打印sql
logging:
  level:
    com.order.mapper : debug
mybatis-plus:
  type-aliases-package:
  mapper-locations:
  global-config:
    refresh-mapper: true
    #驼峰下划线转换
    column-underline: true
  configuration:
    map-underscore-to-camel-case: true